In [1]:
import torch

- ### Introduction to Tensors :

In [2]:
# creating tensor:

scaler = torch.tensor(3)
scaler

tensor(3)

In [3]:
scaler.ndim

0

In [4]:
# back to python int
scaler.item()

3

In [5]:
vector = torch.tensor([4, 9])
vector

tensor([4, 9])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[1, 4], [3, 6]])
MATRIX

tensor([[1, 4],
        [3, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([
    [[1, 2, 3], 
    [4, 5, 6]], 
    
    [[10, 20, 30],
    [40, 50, 60]], 
    
    [[7, 8, 9], 
    [70, 80, 90]]
])

In [12]:
TENSOR.shape

torch.Size([3, 2, 3])

In [13]:
TENSOR[2]

tensor([[ 7,  8,  9],
        [70, 80, 90]])

In [14]:
TENSOR2 = torch.tensor([
    [[1, 5], 
    [4, 3]], 
    
    [[8, 1], 
    [6, 4]], 
    
    [[12, 7],
    [6, 14]]
])

In [15]:
TENSOR2.shape

torch.Size([3, 2, 2])

In [16]:
TENSOR2[1]

tensor([[8, 1],
        [6, 4]])

- ### Random Tensors :

why?

Neural Networks :

`start with random tensors -> look at data -> update random numbers -> look at data -> update random`

In [17]:
random_tensor1= torch.rand(2, 3, 3)
random_tensor1

tensor([[[0.5198, 0.7818, 0.5274],
         [0.2776, 0.7341, 0.6879],
         [0.1551, 0.5012, 0.3841]],

        [[0.8880, 0.3471, 0.0264],
         [0.2400, 0.0685, 0.3604],
         [0.1118, 0.5051, 0.9488]]])

In [18]:
# create a random tensor similar to an image :
image_tensor = torch.rand(size=(3, 224, 224)) #channels, height, width
image_tensor[0]

tensor([[0.3221, 0.7591, 0.6561,  ..., 0.8168, 0.7022, 0.6579],
        [0.4850, 0.7044, 0.6668,  ..., 0.4670, 0.4865, 0.7605],
        [0.5663, 0.5219, 0.6378,  ..., 0.6195, 0.3375, 0.2708],
        ...,
        [0.4030, 0.2368, 0.4849,  ..., 0.8596, 0.7218, 0.6712],
        [0.4550, 0.5286, 0.5937,  ..., 0.5447, 0.6193, 0.0510],
        [0.4137, 0.4166, 0.0264,  ..., 0.0528, 0.6694, 0.1131]])

In [19]:
random_tensor2 = torch.rand_like(image_tensor)

In [20]:
### Zeros & Ones ###

In [21]:
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
### Create a range and Tensor-like:

In [25]:
torch.arange(start=4, end=53, step=8)

tensor([ 4, 12, 20, 28, 36, 44, 52])

- ### Tensor datatype:

In [26]:
float_tensor = torch.tensor([1.0, 5.0, 9.0], 
                            dtype = None, # related to precision in computing
                            device= None, # default:"cpu", on GPU:"cuda"
                            requires_grad = False # track gradients with this tensor operations
)
float_tensor

tensor([1., 5., 9.])

In [27]:
float_tensor.dtype

torch.float32

In [28]:
float_16 = float_tensor.type(torch.float16)
float_16

tensor([1., 5., 9.], dtype=torch.float16)

### Getting information from tensors :

- **shape** - what shape is the tensor? (some operations require specific shape rules)


- **dtype** - what datatype are the elements within the tensor stored in?


- **device** - what device is the tensor stored on? (usually GPU or CPU)

In [29]:
tensor_info = torch.rand(2, 3, 4)
tensor_info

tensor([[[0.3870, 0.0272, 0.9629, 0.6265],
         [0.5730, 0.0691, 0.2504, 0.4691],
         [0.2607, 0.7300, 0.1302, 0.3756]],

        [[0.9239, 0.2473, 0.5031, 0.3819],
         [0.5613, 0.1125, 0.9352, 0.3451],
         [0.7430, 0.9441, 0.7759, 0.7443]]])

In [30]:
tensor_info.shape

torch.Size([2, 3, 4])

In [31]:
tensor_info.dtype

torch.float32

In [32]:
tensor_info.device

device(type='cpu')

In [33]:
tensor_info.size()

torch.Size([2, 3, 4])

### Manipulating Tensors (Tensor Operations)

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- **Matrix multiplication(dot product)**

In [34]:
tensor1 = torch.randint(1, 12, (3,2))
tensor1

tensor([[4, 5],
        [5, 9],
        [7, 7]])

In [35]:
tensor2 = torch.randint(5, 18, (2,4))
tensor2

tensor([[13, 11,  6,  7],
        [ 9,  7, 10, 15]])

In [36]:
# Element wise
print(tensor1)
print('\n')
print(tensor1*tensor1)

tensor([[4, 5],
        [5, 9],
        [7, 7]])


tensor([[16, 25],
        [25, 81],
        [49, 49]])


In [37]:
# Matrix Multiplication
%time

torch.matmul(tensor1, tensor2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[ 97,  79,  74, 103],
        [146, 118, 120, 170],
        [154, 126, 112, 154]])

In [38]:
%%time

tensor1@ tensor2

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[ 97,  79,  74, 103],
        [146, 118, 120, 170],
        [154, 126, 112, 154]])

In [39]:
torch.mm(tensor1, tensor2)

tensor([[ 97,  79,  74, 103],
        [146, 118, 120, 170],
        [154, 126, 112, 154]])

In [40]:
# Transpose : switches axes or dimension
torch.matmul(tensor1, tensor1.T)

tensor([[ 41,  65,  63],
        [ 65, 106,  98],
        [ 63,  98,  98]])

In [41]:
tensor1

tensor([[4, 5],
        [5, 9],
        [7, 7]])

- ### find min, max, mean, sum, etc (Tensor Aggregation)

In [42]:
tensor1.dtype

torch.int64

In [43]:
torch.mean(tensor1, dtype=torch.float32)

tensor(6.1667)

- ### find Positional min and max -> helpful with softmax

In [44]:
tensor3 = torch.randint(5, 25, (3, 4))
tensor3

tensor([[ 9,  6, 13, 14],
        [15, 22,  8, 13],
        [11, 24, 22,  6]])

In [45]:
# position min -> return min index
torch.argmin(tensor3)

tensor(1)

In [46]:
# position max -> return max index
torch.argmax(tensor3)

tensor(9)

### reshaping, stacking, squeeze, unsqueeze

* **torch.reshape(input, shape)** :
Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().


* **torch.Tensor.view(shape) :**
Returns a view of the original tensor in a different shape but shares the same data as the original tensor.


* **torch.stack(tensors, dim=0) :**
Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.


* **torch.squeeze(input) :**
Squeezes input to remove all the dimenions with value 1.


* **torch.unsqueeze(input, dim) :**
Returns input with a dimension value of 1 added at dim.


* **torch.permute(input, dims):**
Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [47]:
my_tensor1 = torch.randint(0, 5, (2, 2))
my_tensor1

tensor([[4, 3],
        [3, 3]])

In [48]:
my_tensor2 = torch.randint(10, 20, (2, 2))
my_tensor2

tensor([[16, 19],
        [15, 13]])

In [49]:
torch.stack([my_tensor1, my_tensor2], dim=0)

tensor([[[ 4,  3],
         [ 3,  3]],

        [[16, 19],
         [15, 13]]])

In [50]:
torch.hstack([my_tensor1, my_tensor2])

tensor([[ 4,  3, 16, 19],
        [ 3,  3, 15, 13]])

In [51]:
torch.vstack([my_tensor1, my_tensor2])

tensor([[ 4,  3],
        [ 3,  3],
        [16, 19],
        [15, 13]])

In [55]:
torch.squeeze(my_tensor1)

tensor([[4, 3],
        [3, 3]])

In [59]:
## Squeeze ## : removes all single dimensions from a target tensor
x1 = torch.rand(1, 3, 1)
x1

tensor([[[0.4502],
         [0.1566],
         [0.3254]]])

In [60]:
x1.shape

torch.Size([1, 3, 1])

In [61]:
y1 = torch.squeeze(x1)
y1

tensor([0.4502, 0.1566, 0.3254])

In [62]:
y1.shape

torch.Size([3])

In [63]:
print("Pre Squeeze Tensor :\n" , x1)
print("Tensor shape :\n", x1.shape)


print('\nSqueezing...\n')

print("New Tensor :\n", y1)
print("Tensor shape :\n", y1.shape)

Pre Squeeze Tensor :
 tensor([[[0.4502],
         [0.1566],
         [0.3254]]])
Tensor shape :
 torch.Size([1, 3, 1])

Squeezing...

New Tensor :
 tensor([0.4502, 0.1566, 0.3254])
Tensor shape :
 torch.Size([3])


In [64]:
## unsqueeze## : add a single dimension to a target tensor at specific dimension

print('pre target :\n', y1)
print('pre target shape :\n', y1.shape)

# add extra dim with unsqueeze:
z1 = torch.unsqueeze(y1, dim=0)
print('New tensor :\n', z1)
print('New shape :\n', z1.shape)

pre target :
 tensor([0.4502, 0.1566, 0.3254])
pre target shape :
 torch.Size([3])
New tensor :
 tensor([[0.4502, 0.1566, 0.3254]])
New shape :
 torch.Size([1, 3])


In [65]:
## permute ## rearranges the dimensions of a target tensor
x_original = torch.rand(size=(224, 224, 3)) # height, width, color_channel

# permute returns a different **view** of original tensor
x_permuted = torch.permute(x_original, (2, 0, 1)) # rearrange color channel
x_permuted.shape

torch.Size([3, 224, 224])

- ### PyTorch & Numpy

* Numpy array -> PyTorch tensor : `torch.from_numpy()`

* PyTorch tensor -> Numpy array : `torch.Tensor.numpy()`

In [66]:
import numpy as np

In [67]:
array_ = np.random.randint(1, 20, (3,3))
array_

array([[ 5, 14,  6],
       [15, 11, 15],
       [ 3, 14,  6]])

In [68]:
torch.from_numpy(array_)

tensor([[ 5, 14,  6],
        [15, 11, 15],
        [ 3, 14,  6]], dtype=torch.int32)

In [76]:
torch.Tensor.numpy(my_tensor1)

array([[4, 3],
       [3, 3]], dtype=int64)

In [71]:
my_tensor1.numpy()

array([[4, 3],
       [3, 3]], dtype=int64)

- ### Reproducibility (trying to take random out of random)

In [72]:
torch.manual_seed(42)
TensorA = torch.rand((3, 3))

torch.manual_seed(42)
TensorB = torch.rand((3, 3))

print(TensorA == TensorB)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Access GPU

- running tensors and Pytorch objects on GPU (and Making faster computations)

* setup device-agnostic code

- **Putting tensors(and models) on the GPU -> Faster numerical calculations** 

In [73]:
# verify GPU:
torch.cuda.is_available()

True

In [74]:
# GPU availability

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [75]:
torch.cuda.device_count()

1

In [78]:
# move tesnsor to GPU if available:
print(tensor1, tensor1.device)

tensor([[4, 5],
        [5, 9],
        [7, 7]]) cpu


In [81]:
tensor_gpu = my_tensor1.to(device)
tensor_gpu

tensor([[4, 3],
        [3, 3]], device='cuda:0')

In [82]:
### If tensor is on the GPU, cant transform it to numpy ###
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [84]:
# GPU Tensor -> cpu -> numpy
tensor_gpu.cpu().numpy()

array([[4, 3],
       [3, 3]], dtype=int64)