## Sample Workflow :

- ### 1: data (prepare and load)
- ### 2: bulid model
- ### 3: fitting the model to data (Training)
- ### 4: making prediction and evaluating a model
- ### 5: saving amd loading a model
- ### 6: putting it all togother


In [2]:
import torch 
from torch import nn # nn contains all pytorch building blocks for neural networks
import matplotlib.pyplot as plt

- ### Data: Preparig and loading

#### data can be almost anything...
* Tabular data
* Images
* Videos
* Audio
* DNA
* Text

Machine learning is a game of two parts:
1. Get data into numerical representation.
2. Build Proper Model For learning that.

### Use linear regression formula to make a straight line with **known parameters**

In [3]:
weight = 0.7
bias = 0.3

In [4]:
# create data
start = 0
end = 1
step = 0.02

X = torch.arange(start, end, step)
X[:5]

tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800])

In [5]:
X.shape

torch.Size([50])

In [6]:
X = X.unsqueeze(dim=1)
X[:5]

tensor([[0.0000],
        [0.0200],
        [0.0400],
        [0.0600],
        [0.0800]])

In [7]:
X.shape

torch.Size([50, 1])

In [8]:
y = X * weight + bias

In [9]:
X[:5], y[:5]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560]]))

In [10]:
### spliting data into train and test sets ###

In [11]:
train_split = int(0.8 * len(X))

X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [11]:
### Visualize our data ###

In [12]:
def plot_prediction(train_data=X_train, train_labels=y_train,
                    test_data=X_test, test_labels=y_test, 
                    predictions=None):
    """
    plot training and test data and compare them with predictions
    
    """
    
    plt.figure(figsize=(10, 7))
    # trainind data
    plt.scatter(train_data, train_labels, c='b', s=4, label='Training data')
    # test data
    plt.scatter(test_data, test_labels, c='r', s=4, label='Testing data')
    
    # plot the predictions if they exists:
    if predictions is not None:
        plt.scatter(test_data, predictions, c='g', s=4, label='Predictions')
         
            
    plt.legend();
    
    

In [13]:
# plot_prediction();

- ### Building first Model

our model :
- Start with random values
- Look at tgraining data
- Adjust random values to better represent(or get closer to) the ideal values

How to adjust?
- 1. Gradient decent
- 2. BackPropagation

In [14]:
### Create Linear Regressin Python Classes ###

In [ ]:
class LinearRegression(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.rand(1, dtype=torch.float, requires_grad=True))
        self.bias = nn.Parameter(torch.rand(1, dtype=torch.float, requires_grad=True))
        
        # Forward method to define computation in the model :
        def forward(self, x:torch.Tensor) -> torch.Tensor: # x is the input data
            return self.weights * x + self.bias
