In [1]:
import torch

- ### Introduction to Tensors :

In [2]:
# creating tensor:

scaler = torch.tensor(3)
scaler

tensor(3)

In [3]:
scaler.ndim

0

In [4]:
# back to python int
scaler.item()

3

In [5]:
vector = torch.tensor([4, 9])
vector

tensor([4, 9])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[1, 4], [3, 6]])
MATRIX

tensor([[1, 4],
        [3, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([
    [[1, 2, 3], 
    [4, 5, 6]], 
    
    [[10, 20, 30],
    [40, 50, 60]], 
    
    [[7, 8, 9], 
    [70, 80, 90]]
])

In [12]:
TENSOR.shape

torch.Size([3, 2, 3])

In [13]:
TENSOR[2]

tensor([[ 7,  8,  9],
        [70, 80, 90]])

In [14]:
TENSOR2 = torch.tensor([
    [[1, 5], 
    [4, 3]], 
    
    [[8, 1], 
    [6, 4]], 
    
    [[12, 7],
    [6, 14]]
])

In [15]:
TENSOR2.shape

torch.Size([3, 2, 2])

In [16]:
TENSOR2[1]

tensor([[8, 1],
        [6, 4]])

- ### Random Tensors :

why?

Neural Networks :

`start with random tensors -> look at data -> update random numbers -> look at data -> update random`

In [17]:
random_tensor1= torch.rand(2, 3, 3)
random_tensor1

tensor([[[0.2114, 0.8078, 0.7621],
         [0.8477, 0.5657, 0.6233],
         [0.2525, 0.8945, 0.5868]],

        [[0.1191, 0.9336, 0.5704],
         [0.0780, 0.3438, 0.7488],
         [0.0422, 0.8427, 0.9752]]])

In [18]:
# create a random tensor similar to an image :
image_tensor = torch.rand(size=(3, 224, 224)) #channels, height, width
image_tensor[0]

tensor([[0.6923, 0.6503, 0.9896,  ..., 0.2573, 0.5298, 0.7189],
        [0.1030, 0.5961, 0.8768,  ..., 0.7535, 0.0961, 0.2946],
        [0.9763, 0.2225, 0.1998,  ..., 0.1486, 0.8694, 0.3298],
        ...,
        [0.6996, 0.5320, 0.6097,  ..., 0.6547, 0.4159, 0.8297],
        [0.5658, 0.1209, 0.8035,  ..., 0.8603, 0.7371, 0.6985],
        [0.9442, 0.0258, 0.7913,  ..., 0.3404, 0.7458, 0.1121]])

In [19]:
random_tensor2 = torch.rand_like(image_tensor)

In [20]:
### Zeros & Ones ###

In [21]:
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
### Create a range and Tensor-like:

In [25]:
torch.arange(start=4, end=53, step=8)

tensor([ 4, 12, 20, 28, 36, 44, 52])

- ### Tensor datatype:

In [26]:
float_tensor = torch.tensor([1.0, 5.0, 9.0], 
                            dtype = None, # related to precision in computing
                            device= None, # default:"cpu", on GPU:"cuda"
                            requires_grad = False # track gradients with this tensor operations
)
float_tensor

tensor([1., 5., 9.])

In [27]:
float_tensor.dtype

torch.float32

In [28]:
float_16 = float_tensor.type(torch.float16)
float_16

tensor([1., 5., 9.], dtype=torch.float16)

### Getting information from tensors :

- **shape** - what shape is the tensor? (some operations require specific shape rules)


- **dtype** - what datatype are the elements within the tensor stored in?


- **device** - what device is the tensor stored on? (usually GPU or CPU)

In [30]:
tensor_info = torch.rand(2, 3, 4)
tensor_info

tensor([[[5.9603e-01, 7.0994e-01, 2.8366e-01, 9.7744e-01],
         [2.6968e-01, 6.8937e-01, 3.8064e-01, 6.1002e-01],
         [1.1620e-01, 3.6166e-01, 3.6087e-01, 8.5777e-01]],

        [[3.2064e-01, 9.5797e-01, 6.6612e-01, 4.0722e-01],
         [9.3794e-04, 3.0133e-01, 4.4130e-01, 1.5795e-01],
         [9.9943e-01, 8.8952e-01, 9.6605e-01, 6.9500e-01]]])

In [31]:
tensor_info.shape

torch.Size([2, 3, 4])

In [32]:
tensor_info.dtype

torch.float32

In [33]:
tensor_info.device

device(type='cpu')

In [35]:
tensor_info.size()

torch.Size([2, 3, 4])

### Manipulating Tensors (Tensor Operations)

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- **Matrix multiplication(dot product)**

In [37]:
tensor1 = torch.randint(1, 12, (3,2))
tensor1

tensor([[ 5, 11],
        [ 7,  7],
        [ 5,  7]])

In [38]:
tensor2 = torch.randint(5, 18, (2,4))
tensor2

tensor([[16,  5,  7,  5],
        [15, 10, 14, 14]])

In [47]:
# Element wise
print(tensor1)
print('\n')
print(tensor1*tensor1)

tensor([[ 5, 11],
        [ 7,  7],
        [ 5,  7]])


tensor([[ 25, 121],
        [ 49,  49],
        [ 25,  49]])


In [55]:
# Matrix Multiplication
%time

torch.matmul(tensor1, tensor2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[245, 135, 189, 179],
        [217, 105, 147, 133],
        [185,  95, 133, 123]])

In [56]:
%%time

tensor1@ tensor2

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[245, 135, 189, 179],
        [217, 105, 147, 133],
        [185,  95, 133, 123]])

In [57]:
torch.mm(tensor1, tensor2)

tensor([[245, 135, 189, 179],
        [217, 105, 147, 133],
        [185,  95, 133, 123]])

In [61]:
# Transpose : switches axes or dimension
torch.matmul(tensor1, tensor1.T)

tensor([[146, 112, 102],
        [112,  98,  84],
        [102,  84,  74]])

In [63]:
tensor1

tensor([[ 5, 11],
        [ 7,  7],
        [ 5,  7]])

- ### find min, max, mean, sum, etc (Tensor Aggregation)

In [68]:
tensor1.dtype

torch.int64

In [71]:
torch.mean(tensor1, dtype=torch.float32)

tensor(7.)

- ### find Positional min and max -> helpful with softmax

In [76]:
tensor3 = torch.randint(5, 25, (3, 4))
tensor3

tensor([[23,  6, 13, 17],
        [12,  9, 11, 13],
        [14,  7,  5, 24]])

In [77]:
# position min -> return min index
torch.argmin(tensor3)

tensor(10)

In [78]:
# position max -> return max index
torch.argmax(tensor3)

tensor(11)

### reshaping, stacking, squeeze, unsqueeze

* **torch.reshape(input, shape)** :
Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().


* **torch.Tensor.view(shape) :**
Returns a view of the original tensor in a different shape but shares the same data as the original tensor.


* **torch.stack(tensors, dim=0) :**
Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.


* **torch.squeeze(input) :**
Squeezes input to remove all the dimenions with value 1.


* **torch.unsqueeze(input, dim) :**
Returns input with a dimension value of 1 added at dim.


* **torch.permute(input, dims):**
Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [103]:
my_tensor1 = torch.randint(0, 5, (2, 2))
my_tensor1

tensor([[4, 0],
        [0, 0]])

In [104]:
my_tensor2 = torch.randint(10, 20, (2, 2))
my_tensor2

tensor([[19, 12],
        [14, 17]])

In [116]:
torch.stack([my_tensor1, my_tensor2], dim=0)

tensor([[[ 4,  0],
         [ 0,  0]],

        [[19, 12],
         [14, 17]]])

In [108]:
torch.hstack([my_tensor1, my_tensor2])

tensor([[ 4,  0, 19, 12],
        [ 0,  0, 14, 17]])

In [109]:
torch.vstack([my_tensor1, my_tensor2])

tensor([[ 4,  0],
        [ 0,  0],
        [19, 12],
        [14, 17]])

In [117]:
torch.squeeze(my_tensor)

tensor([[12, 16,  2,  1],
        [15, 10, 13, 11],
        [ 4,  2,  0,  1]])

In [119]:
my_tensor

tensor([[12, 16,  2,  1],
        [15, 10, 13, 11],
        [ 4,  2,  0,  1]])

In [120]:
## Squeeze ## : removes all single dimensions from a target tensor
x1 = torch.rand(1, 3, 1)
x1

tensor([[[0.2921],
         [0.2677],
         [0.7442]]])

In [121]:
x1.shape

torch.Size([1, 3, 1])

In [123]:
y1 = torch.squeeze(x1)
y1

tensor([0.2921, 0.2677, 0.7442])

In [124]:
y1.shape

torch.Size([3])

In [131]:
print("Pre Squeeze Tensor :\n" , x1)
print("Tensor shape :\n", x1.shape)


print('\nSqueezing...\n')

print("New Tensor :\n", y1)
print("Tensor shape :\n", y1.shape)

Pre Squeeze Tensor :
 tensor([[[0.2921],
         [0.2677],
         [0.7442]]])
Tensor shape :
 torch.Size([1, 3, 1])

Squeezing...

New Tensor :
 tensor([0.2921, 0.2677, 0.7442])
Tensor shape :
 torch.Size([3])


In [135]:
## unsqueeze## : add a single dimension to a target tensor at specific dimension

print('pre target :\n', y1)
print('pre target shape :\n', y1.shape)

# add extra dim with unsqueeze:
z1 = torch.unsqueeze(y1, dim=0)
print('New tensor :\n', z1)
print('New shape :\n', z1.shape)

pre target :
 tensor([0.2921, 0.2677, 0.7442])
pre target shape :
 torch.Size([3])
New tensor :
 tensor([[0.2921, 0.2677, 0.7442]])
New shape :
 torch.Size([1, 3])


In [137]:
## permute ## rearranges the dimensions of a target tensor
x_original = torch.rand(size=(224, 224, 3)) # height, width, color_channel

# permute returns a different **view** of original tensor
x_permuted = torch.permute(x_original, (2, 0, 1)) # rearrange color channel
x_permuted.shape

torch.Size([3, 224, 224])

- ### PyTorch & Numpy

* Numpy array -> PyTorch tensor : `torch.from_numpy()`

* PyTorch tensor -> Numpy array : `torch.Tensor.numpy()`

In [138]:
import numpy as np

In [139]:
array_ = np.random.randint(1, 20, (3,3))
array_

array([[ 5,  6, 18],
       [10,  7, 19],
       [ 4, 16, 19]])

In [140]:
torch.from_numpy(array_)

tensor([[ 5,  6, 18],
        [10,  7, 19],
        [ 4, 16, 19]], dtype=torch.int32)

In [144]:
torch.Tensor.numpy(my_tensor)

array([[12, 16,  2,  1],
       [15, 10, 13, 11],
       [ 4,  2,  0,  1]], dtype=int64)

In [145]:
my_tensor.numpy()

array([[12, 16,  2,  1],
       [15, 10, 13, 11],
       [ 4,  2,  0,  1]], dtype=int64)

- ### Reproducibility (trying to take random out of random)

In [157]:
torch.manual_seed(42)
TensorA = torch.rand((3, 3))

torch.manual_seed(42)
TensorB = torch.rand((3, 3))

print(TensorA == TensorB)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Access GPU

- running tensors and Pytorch objects on GPU (and Making faster computations)

* setup device-agnostic code

In [158]:
# verify GPU:
torch.cuda.is_available()

True

In [159]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [160]:
torch.cuda.device_count()

1